# __Transformación de datos (Feature scaling)__

Vamos a implementar MinMaxScaler y StandardScaler de Sklearn, tanto en un dataset de juguete como en el dataset `titanic.csv`

In [1]:
# Ubicación de los dataset
path_juguete = "https://drive.google.com/uc?id=1pfwAP_lYaS2EgoZGUtjzmy35QBrynQ6I&export=download"
path_titanic = "https://drive.google.com/uc?id=1KsLlUKjtnin2N2_EHugykz-wBaP8Gh4L&export=download"

## Lectura de los dataset

In [2]:
# pandas nos permite leer los dataset fácilmente
import pandas as pd

In [3]:
# Leer ambos dataset de una vez
df_juguete = pd.read_csv(path_juguete)
df_titanic = pd.read_csv(path_titanic)

In [4]:
# mostrar dataset de juguete
df_juguete

    x1  x2
0  928   3
1  641   6
2  700   7
3  901   7
4  596   0
5  706   5

In [5]:
# mostrar dataset del titanic
df_titanic.sample(5)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
321,1,2,Mrs. Albert Francis (Sylvia Mae Harbaugh) Cald...,female,22.0,1,1,29.0000
658,0,3,Mr. Mohamed Badt,male,40.0,0,0,7.2250
189,1,2,Mrs. (Rosa) Pinsky,female,32.0,0,0,13.0000
99,0,3,Miss. Matilda Petranec,female,28.0,0,0,7.8958
147,0,2,Mr. Michel Navratil,male,36.5,0,2,26.0000

## ¡A transformar!

Vamos a usar la librería de sklearn para realizar las transformaciones (Min - Max Scaler y Standard Scaler) en el dataset de juguete.

In [6]:
# importar transformaciones
from sklearn.preprocessing import MinMaxScaler, StandardScaler

En el siguiente paso, instanciamos dos objetos de cada clase importada

In [7]:
# Instanciación de los objetos escaladores
scaler_minmax = MinMaxScaler()
scaler_standard = StandardScaler()

## Standard Scaler

El primer método que vamos a ver es `fit_transform` de `StandardScaler` (Si aprendes a usar este, `MinMaxScaler` será pan comido porque ambas clases se usan prácticamente igual).
Como es de costumbre, es importante que leas la documentación, esto te permitirá comprender qué tanto puedes hacer con estas clases.

A continuación te dejamos las dos documentaciones:


*   [Documentación de MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#:~:text=Transform%20features%20by%20scaling%20each,e.g.%20between%20zero%20and%20one.)
*   [Documentación de StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

In [8]:
# Transformamos el dataset
df_scaled = scaler_standard.fit_transform(df_juguete)

# Mostramos el dataset transformado
df_scaled

array([[ 1.45639128, -0.6681531 ],
       [-0.83184393,  0.53452248],
       [-0.36144017,  0.93541435],
       [ 1.24112177,  0.93541435],
       [-1.19062645, -1.87082869],
       [-0.3136025 ,  0.13363062]])

Si quisiéramos conocer las varianzas de cada columna antes de ser transformada, podemos conocerlas imprimiendo el atributo `var_`

**Nota: La desviación estándar se define como la raíz cuadrada de la varianza, es decir:** $\sigma=\sqrt{var}$

In [9]:
# Imprimimos las varianzas
scaler_standard.var_

array([1.57312222e+04, 6.22222222e+00])

In [10]:
# Importamos numpy para aplicar operaciones vectoriales (Sacar la raíz de un vector)
import numpy as np

# Sacamos la raíz de cada componente
np.sqrt(scaler_standard.var_)

array([125.42416921,   2.49443826])

Ahora, para conocer las medias de cada columna antes de ser escalada, imprimimos el atributo `mean_`

In [11]:
# Imprimimos las medias
scaler_standard.mean_

array([745.33333333,   4.66666667])

Cabe resaltar que el método `fit_transform` se olvida de los nombres de las columnas (`x1` y `x2` en este caso) porque el resultado que retorna es un objeto de la clase `numpy.ndarray`, ¡Vamos a comprobarlo en la siguiente celda de código!

In [12]:
# Imprimimos el tipo de dato que guarda la variable df_scaled
print( type(df_scaled) )

<class 'numpy.ndarray'>

Para volver a colocarle nombre a las columnas, hacemos lo siguiente

In [13]:
df_scaled = pd.DataFrame(df_scaled, columns=df_juguete.columns)
df_scaled

         x1        x2
0  1.456391 -0.668153
1 -0.831844  0.534522
2 -0.361440  0.935414
3  1.241122  0.935414
4 -1.190626 -1.870829
5 -0.313603  0.133631

## MinMaxScaler

In [14]:
# transformamos el dataset con minmaxscaler
df_scaled_minmax = scaler_minmax.fit_transform(df_juguete)
df_scaled_minmax

array([[1.        , 0.42857143],
       [0.13554217, 0.85714286],
       [0.31325301, 1.        ],
       [0.9186747 , 1.        ],
       [0.        , 0.        ],
       [0.3313253 , 0.71428571]])

Para ponerle nuevamente el nombre a las columnas ejecutamos la siguiente celda de código

In [15]:
df_scaled_minmax = pd.DataFrame(df_scaled_minmax, columns=df_juguete.columns)
df_scaled_minmax

         x1        x2
0  1.000000  0.428571
1  0.135542  0.857143
2  0.313253  1.000000
3  0.918675  1.000000
4  0.000000  0.000000
5  0.331325  0.714286

## Feature Scaling sobre los datos del Titanic

Ahora trabajaremos sobre el dataset del titanic (Lo limpiaremos, y tu trabajo será aplicar MinMaxScaler y StandardScaler)

In [ ]:
# Imprimimos 5 muestras aleatorias del dataset del titanic
df_titanic.sample(5)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
734,0,3,Mr. Kanio Ivanoff,male,20.0,0,0,7.8958
356,1,3,Miss. Mary McGovern,female,22.0,0,0,7.8792
38,0,3,Miss. Augusta Maria Vander Planke,female,18.0,2,0,18.0000
135,1,1,Miss. Helen Monypeny Newsom,female,19.0,0,2,26.2833
412,1,3,Mr. Johan Julian Sundman,male,44.0,0,0,7.9250

La columna de nombres de los pasajeros no es relevante, por lo que procederemos a eliminarla haciendo uso del método `drop`.
(También eliminaremos la columna `Sex`, la próxima semana aprenderemos a darle manejo a los datos categóricos)

[Documentación del método drop](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html)

In [ ]:
# Eliminamos la columna 'Name' de df_titanic (Modificando df_titanic)
df_titanic.drop(columns=['Name', 'Sex'], inplace=True)

# Verificamos que se haya eliminado la columna 'Name'
df_titanic.head()

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,22.0,1,0,7.2500
1,1,1,38.0,1,0,71.2833
2,1,3,26.0,0,0,7.9250
3,1,1,35.0,1,0,53.1000
4,0,3,35.0,0,0,8.0500

# Reto 4 (10%)
El estudiante deberá tomar el dataset del titanic (Puede descargarlo dando clic [aquí](https://drive.google.com/uc?id=1KsLlUKjtnin2N2_EHugykz-wBaP8Gh4L&export=download)) y realizar las siguientes operaciones sobre él:

1.   Eliminar las columnas 'Name' y 'Sex'.
2.   Aplicar MinMaxScaler sobre el dataframe resultante de eliminar las dos columnas del punto 1 (No olvidar volver a colocarle el nombre a las columnas).
3.   Aplicar StandardScaler sobre el dataframe resultante de eliminar las dos columnas del punto 1 (No olvidar volver a colocarle el nombre a las columnas).
4. Extraer la desviación estándar y la media aritmética de cada columna (Haciendo uso de los métodos y atributos proporcionados por la clase [StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) y [numpy](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html))