# __Reto 4: Transformacion de datos__

## Objetivo

Aplicar las dos técnicas de escalado de datos vistas en la semana 5

## Tarea 1

Cargar el dataset del titanic y eliminar las columnas 'Name' y 'Sex'.

In [1]:
# librerias
import pandas as pd
import numpy as np

In [2]:
# cargar datos
df = pd.read_csv('./titanic.csv')
df.sample(5)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
660,0,3,Mr. Peju Coleff,male,36.0,0,0,7.4958
359,0,2,Mr. Sebastiano del Carlo,male,29.0,1,0,27.7208
139,0,3,Mrs. Joseph (Sultana) Boulos,female,40.0,0,2,15.2458
816,1,1,Mrs. Charles Melville (Clara Jennings Gregg) Hays,female,52.0,1,1,93.5000
605,1,2,Mrs. Joseph (Juliette Marie Louise Lafargue) L...,female,22.0,1,2,41.5792

In [3]:
# eliminar variables Name y Sex
df.drop(columns=['Name', 'Sex'], inplace=True)
df.sample(5)

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
629,1,1,32.00,0,0,30.5000
760,0,3,16.00,0,0,7.7750
204,0,3,2.00,0,1,10.4625
751,1,2,0.67,1,1,14.5000
640,1,3,32.00,0,0,56.4958

## Tarea 2

Aplicar MinMaxScaler sobre el dataframe resultante de eliminar las dos columnas del punto 1 (no olvidar volver a ponerle el nombre a las columnas)

In [ ]:
# importar transformaciones
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
# Instanciar los objetos escaladores
scaler_minmax = MinMaxScaler()
scaler_standard = StandardScaler()

In [ ]:
# transformar el dataset con minmaxscaler
df_scaled_minmax = scaler_minmax.fit_transform(df)
df_scaled_minmax

array([[0.        , 1.        , 0.27117366, 0.125     , 0.        ,
        0.01415106],
       [1.        , 0.        , 0.4722292 , 0.125     , 0.        ,
        0.13913574],
       [1.        , 1.        , 0.32143755, 0.        , 0.        ,
        0.01546857],
       ...,
       [0.        , 1.        , 0.08268409, 0.125     , 0.33333333,
        0.04577135],
       [1.        , 0.        , 0.32143755, 0.        , 0.        ,
        0.0585561 ],
       [0.        , 1.        , 0.39683338, 0.        , 0.        ,
        0.01512699]])

In [ ]:
# agregar el nombre de las columnas
df_scaled_minmax = pd.DataFrame(df_scaled_minmax, columns=df.columns)
df_scaled_minmax

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0.0,1.0,0.271174,0.125,0.000000,0.014151
1,1.0,0.0,0.472229,0.125,0.000000,0.139136
2,1.0,1.0,0.321438,0.000,0.000000,0.015469
3,1.0,0.0,0.434531,0.125,0.000000,0.103644
4,0.0,1.0,0.434531,0.000,0.000000,0.015713
...,...,...,...,...,...,...
882,0.0,0.5,0.334004,0.000,0.000000,0.025374
883,1.0,0.0,0.233476,0.000,0.000000,0.058556
884,0.0,1.0,0.082684,0.125,0.333333,0.045771
885,1.0,0.0,0.321438,0.000,0.000000,0.058556
886,0.0,1.0,0.396833,0.000,0.000000,0.015127

## Tarea 3

Aplicar StandardScaler sobre el dataframe resultante de eliminar las dos columnas del punto 1 (no olvidar volver a ponerle el nombre a las columnas).

In [ ]:
# transformar el dataset con Standard Scaler
df_scaled = scaler_standard.fit_transform(df)
df_scaled

array([[-0.79216345,  0.83052363, -0.52936601,  0.42990395, -0.4749808 ,
        -0.50358635],
       [ 1.26236574, -1.56127657,  0.60426454,  0.42990395, -0.4749808 ,
         0.78341245],
       [ 1.26236574,  0.83052363, -0.24595837, -0.47585568, -0.4749808 ,
        -0.49001959],
       ...,
       [-0.79216345,  0.83052363, -1.59214465,  0.42990395,  2.00330136,
        -0.17798419],
       [ 1.26236574, -1.56127657, -0.24595837, -0.47585568, -0.4749808 ,
        -0.04633641],
       [-0.79216345,  0.83052363,  0.17915309, -0.47585568, -0.4749808 ,
        -0.4935369 ]])

In [ ]:
# agregar los nombres a las columnas
df_scaled = pd.DataFrame(df_scaled, columns=df.columns)
df_scaled

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,-0.792163,0.830524,-0.529366,0.429904,-0.474981,-0.503586
1,1.262366,-1.561277,0.604265,0.429904,-0.474981,0.783412
2,1.262366,0.830524,-0.245958,-0.475856,-0.474981,-0.490020
3,1.262366,-1.561277,0.391709,0.429904,-0.474981,0.417948
4,-0.792163,0.830524,0.391709,-0.475856,-0.474981,-0.487507
...,...,...,...,...,...,...
882,-0.792163,-0.365376,-0.175106,-0.475856,-0.474981,-0.388018
883,1.262366,-1.561277,-0.741922,-0.475856,-0.474981,-0.046336
884,-0.792163,0.830524,-1.592145,0.429904,2.003301,-0.177984
885,1.262366,-1.561277,-0.245958,-0.475856,-0.474981,-0.046336
886,-0.792163,0.830524,0.179153,-0.475856,-0.474981,-0.493537

## Tarea 4

Extraer la desviación estándar y la media aritmética de cada columna (usando los métodos y atributos proporcionados por la clase StandardScaler y numpy).

__Desviacion Estandar de df_scaled__

In [ ]:
# imprimir varianza
scaler_standard.var_

array([2.36905623e-01, 6.99214128e-01, 1.99203462e+02, 1.21891686e+00,
       6.51266128e-01, 2.47545758e+03])

In [ ]:
# obtener la desviacion standard a partir de la raiz cuadrada de la varianza
np.sqrt(scaler_standard.var_)

array([ 0.48672952,  0.83619025, 14.11394567,  1.10404568,  0.80701061,
       49.75397046])

__Media de df_scaled__

In [ ]:
# mostrar las medias de cada variable
scaler_standard.mean_

array([ 0.38556933,  2.30552424, 29.47144307,  0.5253664 ,  0.38331454,
       32.30542018])