# __Reto 4: Transformacion de datos__

## Objetivo

Aplicar las dos técnicas de escalado de datos vistas en la semana 5

## Tarea 1

Cargar el dataset del titanic y eliminar las columnas 'Name' y 'Sex'.

In [1]:
# librerias
import pandas as pd
import numpy as np

In [2]:
# cargar datos
df = pd.read_csv('./titanic.csv')
df.sample(5)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
502,0,1,Mr. Victor de Satode Penasco y Castellana,male,18.0,1,0,108.90
405,1,2,Master. William Rowe Richards,male,3.0,1,1,18.75
667,1,2,Mrs. Thomas William Solomon (Elizabeth Catheri...,female,40.0,1,1,39.00
514,0,3,Mr. Patrick Ryan,male,30.0,0,0,24.15
302,0,3,Mr. Howard Hugh Williams,male,28.0,0,0,8.05

In [3]:
# eliminar variables Name y Sex
df.drop(columns=['Name', 'Sex'], inplace=True)
df.sample(5)

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
84,1,3,33.0,3,0,15.8500
121,0,2,32.5,1,0,30.0708
154,0,1,51.0,0,1,61.3792
756,0,3,23.0,0,0,14.5000
395,0,2,46.0,0,0,26.0000

## Tarea 2

Aplicar MinMaxScaler sobre el dataframe resultante de eliminar las dos columnas del punto 1 (no olvidar volver a ponerle el nombre a las columnas)

In [4]:
# importar transformaciones
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
# Instanciar los objetos escaladores
scaler_minmax = MinMaxScaler()
scaler_standard = StandardScaler()

In [ ]:
# transformar el dataset con minmaxscaler
df_scaled_minmax = scaler_minmax.fit_transform(df)
df_scaled_minmax

array([[0.        , 1.        , 0.27117366, 0.125     , 0.        ,
        0.01415106],
       [1.        , 0.        , 0.4722292 , 0.125     , 0.        ,
        0.13913574],
       [1.        , 1.        , 0.32143755, 0.        , 0.        ,
        0.01546857],
       ...,
       [0.        , 1.        , 0.08268409, 0.125     , 0.33333333,
        0.04577135],
       [1.        , 0.        , 0.32143755, 0.        , 0.        ,
        0.0585561 ],
       [0.        , 1.        , 0.39683338, 0.        , 0.        ,
        0.01512699]])

In [7]:
# agregar el nombre de las columnas
df_scaled_minmax = pd.DataFrame(df_scaled_minmax, columns=df.columns)
df_scaled_minmax

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0.0,1.0,0.271174,0.125,0.000000,0.014151
1,1.0,0.0,0.472229,0.125,0.000000,0.139136
2,1.0,1.0,0.321438,0.000,0.000000,0.015469
3,1.0,0.0,0.434531,0.125,0.000000,0.103644
4,0.0,1.0,0.434531,0.000,0.000000,0.015713
...,...,...,...,...,...,...
882,0.0,0.5,0.334004,0.000,0.000000,0.025374
883,1.0,0.0,0.233476,0.000,0.000000,0.058556
884,0.0,1.0,0.082684,0.125,0.333333,0.045771
885,1.0,0.0,0.321438,0.000,0.000000,0.058556
886,0.0,1.0,0.396833,0.000,0.000000,0.015127