# __Reto 4: Transformacion de datos__

## Objetivo

Aplicar las dos técnicas de escalado de datos vistas en la semana 5

## Tarea 1

Cargar el dataset del titanic y eliminar las columnas 'Name' y 'Sex'.

In [1]:
# librerias
import pandas as pd
import numpy as np

In [2]:
# cargar datos
df = pd.read_csv('./titanic.csv')
df.sample(5)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
502,0,1,Mr. Victor de Satode Penasco y Castellana,male,18.0,1,0,108.90
405,1,2,Master. William Rowe Richards,male,3.0,1,1,18.75
667,1,2,Mrs. Thomas William Solomon (Elizabeth Catheri...,female,40.0,1,1,39.00
514,0,3,Mr. Patrick Ryan,male,30.0,0,0,24.15
302,0,3,Mr. Howard Hugh Williams,male,28.0,0,0,8.05

In [3]:
# eliminar variables Name y Sex
df.drop(columns=['Name', 'Sex'], inplace=True)
df.sample(5)

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
84,1,3,33.0,3,0,15.8500
121,0,2,32.5,1,0,30.0708
154,0,1,51.0,0,1,61.3792
756,0,3,23.0,0,0,14.5000
395,0,2,46.0,0,0,26.0000