# __Reto 3: Limpieza de datos__

## Objetivo

Tomar el dataset ya semiprocesado y limpiar la columna price.

## Tarea 1

Pasar valores de price que estan como cadenas de texto a números.

In [ ]:
# librerias
import pandas as pd
import numpy as np

In [ ]:
# cargar datos
df = pd.read_excel('./audible.xlsx', index_col=0)
df.sample(5)

,name,author,narrator,time,releasedate,language,stars,price,ratings
1883,What Was the San Francisco Earthquake?,"DorothyHoobler,ThomasHoobler,WhoHQ",AkainaGhosh,5,2021-05-10,English,0.0,351,0
67776,Bloodline of the Gods,NickRedfern,ShaunGrindell,458,2016-03-22,English,2.5,703,2
42893,"On ne naît pas féministe, on le devient",JuliaPietri,ManonJomain,153,2021-06-10,french,0.0,756,0
21819,We Will Not Go to Tuapse,FernandKaisergruber,PaulWoodson,1120,2018-03-20,English,0.0,836,0
71087,Short Stories by Anton Chekhov,AntonChekhov,MichaelRedgrave,44,2013-01-01,English,0.0,303,0

In [ ]:
# mostrar el tipo de dato para cada columna
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87489 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  int64
 4   releasedate  87489 non-null  datetime64[ns]
 5   language     87489 non-null  object
 6   stars        87489 non-null  float64
 7   price        87489 non-null  object
 8   ratings      87489 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 6.7+ MB

In [ ]:
# listar registros que contienen como valor 'Free' en price
df[df['price'] == 'Free'].index.tolist()

[1414,
 1513,
 2932,
 4547,
 5247,
 6725,
 6808,
 6826,
 6848,
 7736,
 9277,
 11754,
 12490,
 12500,
 12509,
 12515,
 12523,
 12530,
 12559,
 12564,
 12565,
 12575,
 12576,
 12577,
 12584,
 12585,
 12586,
 12587,
 12588,
 12590,
 12607,
 12612,
 12618,
 12636,
 12641,
 12642,
 12644,
 12650,
 12652,
 12655,
 12707,
 12708,
 12709,
 12747,
 12778,
 12779,
 12780,
 12813,
 12814,
 12815,
 12834,
 12837,
 12855,
 12856,
 12857,
 12860,
 12888,
 12889,
 12890,
 12891,
 12892,
 12893,
 12894,
 12899,
 12993,
 12998,
 13000,
 13003,
 13004,
 13085,
 13091,
 13094,
 13095,
 13103,
 13251,
 13253,
 13256,
 13257,
 13258,
 13259,
 13260,
 13261,
 13264,
 13268,
 13270,
 13273,
 13274,
 13275,
 13276,
 13839,
 13841,
 14279,
 14280,
 16717,
 17917,
 18361,
 18651,
 18753,
 18754,
 18756,
 18758,
 18831,
 18835,
 18837,
 18839,
 18842,
 18887,
 18888,
 18890,
 18896,
 18897,
 18900,
 18936,
 18937,
 19433,
 19547,
 19562,
 19998,
 20235,
 20255,
 20266,
 21278,
 22175,
 22181,
 22375,
 23030,
 23056,
 23071,
 23074,
 25753,
 26477,
 26808,
 27444,
 28478,
 29518,
 29521,
 30021,
 30325,
 30824,
 31993,
 32523,
 32637,
 32661,
 33157,
 34237,
 34260,
 34972,
 35358,
 35377,
 35602,
 35622,
 35997,
 36054,
 37357,
 37390,
 37403,
 37597,
 37620,
 37659,
 37729,
 37846,
 37852,
 38691,
 40196,
 42887,
 44526,
 44642,
 44739,
 47093,
 47095,
 47102,
 47112,
 47119,
 47121,
 47126,
 47137,
 47150,
 47151,
 47237,
 47289,
 47293,
 48006,
 48085,
 48145,
 48171,
 48176,
 48188,
 48190,
 48193,
 48203,
 48212,
 48215,
 48220,
 48225,
 48230,
 48247,
 48255,
 48258,
 48260,
 48262,
 48269,
 48272,
 48276,
 48277,
 48291,
 48333,
 48404,
 48689,
 49084,
 49086,
 49828,
 49914,
 49942,
 49973,
 49977,
 50042,
 50235,
 50296,
 50297,
 50323,
 50340,
 50467,
 50549,
 50575,
 50590,
 50625,
 50631,
 50637,
 50818,
 51327,
 51332,
 52252,
 53131,
 53333,
 53337,
 53389,
 53689,
 55205,
 55667,
 55668,
 55671,
 55865,
 56671,
 57149,
 57902,
 59179,
 59197,
 59198,
 59216,
 59463,
 60133,
 60182,
 60855,
 60922,
 62005,
 62316,
 62453,
 62458,
 62476,
 62490,
 62499,
 62511,
 62525,
 62536,
 62544,
 62554,
 62557,
 62569,
 62653,
 62733,
 63838,
 64441,
 64455,
 64485,
 64526,
 64893,
 64937,
 66182,
 66450,
 66451,
 66452,
 66453,
 66454,
 66455,
 66459,
 66460,
 66487,
 66488,
 66489,
 66490,
 66492,
 66494,
 66495,
 66496,
 66889,
 66895,
 66896,
 66898,
 66901,
 66902,
 66903,
 71086,
 71382,
 71384,
 71386,
 71387,
 71396,
 71404,
 71405,
 71408,
 71411,
 71414,
 71418,
 71419,
 71422,
 71429,
 71430,
 71443,
 71455,
 71456,
 71490,
 71496,
 71511,
 71792,
 71977,
 76400,
 76861,
 76914,
 79099,
 79795,
 79920,
 79944,
 80021,
 81198,
 82644,
 86771,
 86927]

In [ ]:
# convertir registros con valor 'Free' en 0
df.loc[df['price'] == 'Free', 'price'] = 0
df[df['price'] == 'Free'].index.tolist()

[]

In [ ]:
# verificar los tipos de datos que hay en Price
df['price'].apply(type).value_counts()

price
<class 'int'>      87487
<class 'float'>        2
Name: count, dtype: int64

## Tarea 2

Pasar columna price a tipo float64.

In [29]:
df['price'] = pd.to_numeric(df['price'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87489 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  object
 1   author       87489 non-null  object
 2   narrator     87489 non-null  object
 3   time         87489 non-null  int64
 4   releasedate  87489 non-null  datetime64[ns]
 5   language     87489 non-null  object
 6   stars        87489 non-null  float64
 7   price        87489 non-null  float64
 8   ratings      87489 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 8.7+ MB

In [31]:
df.sample(10)

,name,author,narrator,time,releasedate,language,stars,price,ratings
11211,Contenido dinámico vs contenido personalizado ...,ISDIDigitalTalent,JuanArenas,12,2020-10-29,spanish,0.0,268.0,0
83885,The Power of Five: Oblivion,AnthonyHorowitz,PaulPanting,1320,2020-01-30,English,5.0,645.0,1
8777,A tizennégy karátos autó,RejtőJenő,RudolfPéter,417,2019-04-25,hungarian,0.0,468.0,0
36518,Psychotherapy East and West,AlanWatts,JeremyArthur,336,2019-12-03,English,0.0,134.0,0
50824,Fighting Fate,Tinalynge,TristanMorris,645,2021-12-14,English,0.0,1172.0,0
72539,Турнир драконов [Tournament of Dragons],JuliaKanevskaya,GalinaKejnz,552,2021-07-27,russian,0.0,234.0,0
536,Hello Kitty - La excursión escolar,"Sanrio,NeusCasanovaVico",EvaAndrés,40,2021-10-11,spanish,0.0,38.0,0
40905,Spy Wars,TenentHBagley,TenentHBagley,634,2010-10-03,English,0.0,836.0,0
20109,Still Foolin' Em,BillyCrystal,BillyCrystal,482,2015-08-27,English,4.5,683.0,3
27019,Lebenswerk,AliceSchwarzer,AliceSchwarzer,624,2020-10-11,german,0.0,468.0,0

## Tarea 3

Verificar la suma de los valores price

In [30]:
df['price'].sum()

48907159.9