# __Reto 5: Adicion de variables__

## Objetivo

Saber qué método de codificación usar cuando se enfrenta a variables categóricas nominales y ordinales

## Tarea 1

Cargar el dataset modificado Breast Cancer

In [1]:
# librerias
import pandas as pd
import numpy as np

In [4]:
# cargar datos
df = pd.read_excel('./breast-cancer-modified.xlsx', index_col=0)
df.sample(5)

        age menopause deg-malig  breast irradiat                  Class
44   30-39'  premeno'        1'   left'      no'  no-recurrence-events'
146  30-39'  premeno'        2'  right'     yes'     recurrence-events'
217  50-59'  premeno'        2'   left'      no'  no-recurrence-events'
37   60-69'     ge40'        3'   left'      no'  no-recurrence-events'
218  60-69'     ge40'        1'  right'     yes'     recurrence-events'

## Tarea 2

Aplicar la codificacion correspondiente dependiendo de la informacion de cada variable

__age: Ordinal__

In [5]:
df.age.unique()

array(["40-49'", "50-59'", "60-69'", "30-39'", "70-79'", "20-29'"],
      dtype=object)

In [6]:
# importar OrdinalEncoder
from sklearn.preprocessing import OrdinalEncoder

# instanciar el objeto ordinalencoder
# agregar enn orden las categorias
encoder = OrdinalEncoder(categories=[["20-29'", "30-39'", "40-49'", "50-59'", "60-69'",  "70-79'"]])

In [9]:
# ajustar y transformar el encoder
age_ordinal = encoder.fit_transform(df[['age']])

# concatenar valores codificados el dataframe original
df['age_encoded'] = age_ordinal

df.sample(5)

,age,menopause,deg-malig,breast,irradiat,Class,age_encoded
214,40-49',premeno',2',right',no',no-recurrence-events',2.0
71,60-69',ge40',1',right',yes',no-recurrence-events',4.0
14,40-49',premeno',2',left',yes',recurrence-events',2.0
154,60-69',ge40',2',left',no',no-recurrence-events',4.0
165,50-59',ge40',2',left',yes',recurrence-events',3.0

__Variables Nominales: menopause, breast, irradiat, Class__

In [10]:
# codificar todas las variables nominales en un mismo paso
var_nominal = pd.get_dummies(df[['menopause', 'breast', 'irradiat', 'Class']])
var_nominal

,menopause_ge40',menopause_lt40',menopause_premeno',breast_left',breast_right',irradiat_no',irradiat_yes',Class_no-recurrence-events',Class_recurrence-events'
0,False,False,True,False,True,True,False,False,True
1,True,False,False,False,True,True,False,True,False
2,True,False,False,True,False,True,False,False,True
3,False,False,True,False,True,False,True,True,False
4,False,False,True,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...
281,True,False,False,True,False,True,False,True,False
282,False,False,True,True,False,False,True,True,False
283,False,False,True,False,True,True,False,True,False
284,False,False,True,False,True,True,False,True,False
285,True,False,False,True,False,True,False,True,False

In [11]:
# concatenar variables codificadas al dataframe original
df = pd.concat([df, var_nominal], axis=1)
df.sample(5)

,age,menopause,deg-malig,breast,irradiat,Class,age_encoded,menopause_ge40',menopause_lt40',menopause_premeno',breast_left',breast_right',irradiat_no',irradiat_yes',Class_no-recurrence-events',Class_recurrence-events'
264,50-59',ge40',3',left',yes',no-recurrence-events',3.0,True,False,False,True,False,False,True,True,False
11,60-69',ge40',2',right',no',no-recurrence-events',4.0,True,False,False,False,True,True,False,True,False
16,50-59',premeno',1',right',no',no-recurrence-events',3.0,False,False,True,False,True,True,False,True,False
257,60-69',ge40',3',left',yes',recurrence-events',4.0,True,False,False,True,False,False,True,False,True
9,40-49',ge40',2',right',yes',no-recurrence-events',2.0,True,False,False,False,True,False,True,True,False